"""Generate the C++ translation unit that embeds the WebUI into the firmware.

Every file in ``data/web/`` is gzipped and emitted as a byte array in
``web_assets_generated.cpp`` (with matching declarations in
``web_assets_generated.hpp``), which ``components/pf_web`` compiles into the
app image.  A single OTA download therefore updates the firmware and the
frontend together -- see
``docs/adr/0016-embed-webui-assets-in-firmware.md``.

Why a generated translation unit rather than ESP-IDF's ``EMBED_FILES`` /
``target_add_binary_data()``: those attach the payload through a build-time
CMake custom command, but PlatformIO does not run the CMake/ninja build.  It
reads the CMake File API code model and compiles the reported sources with
SCons, so a source that only materialises during the ninja build fails with
"Source ... not found".  A checked-in-shaped generated ``.cpp`` sitting at a
fixed path exists at configure time, so the code model sees it and SCons
compiles it like any other source.

The generator runs twice, which is deliberate:

* at CMake configure time, so the file exists before the code model is built;
* from ``tools/platformio_web_assets.py`` before every PlatformIO build, so
  edits to ``data/web/*`` land in the firmware without a CMake reconfigure
  (PlatformIO only reconfigures when the root or ``src`` CMakeLists changes).

Output is deterministic and only written when the content actually changes:
the gzip header carries no filename and a zero mtime, so an untouched asset
never churns the firmware image or triggers a needless rebuild.
"""

import argparse
import gzip
import io
import pathlib
import sys

BYTES_PER_LINE = 16

BANNER = """// AUTO-GENERATED by tools/generate_web_assets.py -- DO NOT EDIT.
//
// Source: data/web/ (gzip -9, deterministic: no filename, mtime=0).
// Regenerated automatically before every build; see the script's docstring
// and docs/adr/0016-embed-webui-assets-in-firmware.md.
"""


def to_identifier(name: str) -> str:
    """index.html -> IndexHtml, image_pfr1.js -> ImagePfr1Js

    ASCII-only on purpose: test/web/test_embedded_web_assets.mjs derives the
    same symbol with a JavaScript regex that treats every non-ASCII character
    as a separator. Accepting str.isalnum()'s wider Unicode notion here would
    make the two sides disagree and fail the contract test for an asset that
    is in fact wired up correctly.
    """
    cleaned = "".join(
        character if character.isascii() and character.isalnum() else " "
        for character in name)
    return "".join(word[:1].upper() + word[1:] for word in cleaned.split())


def compress(payload: bytes) -> bytes:
    buffer = io.BytesIO()
    with gzip.GzipFile(
        filename="",
        mode="wb",
        fileobj=buffer,
        compresslevel=9,
        mtime=0,
    ) as compressed:
        compressed.write(payload)
    return buffer.getvalue()


def collect(source_directory: pathlib.Path):
    assets = []
    claimed = {}
    for path in sorted(source_directory.iterdir()):
        if not path.is_file() or path.name.startswith("."):
            continue
        # Printable ASCII only: the name becomes both a C++ identifier and a
        # comment in the generated source, so a control character could break
        # the output outright.
        if not path.name.isascii() or not path.name.isprintable():
            raise SystemExit(
                f"generate_web_assets: asset name must be printable ASCII: "
                f"{path.name!r}. Rename it: the embedded symbol is derived "
                "from the filename and must be a portable C++ identifier.")
        raw = path.read_bytes()
        if not raw:
            raise SystemExit(f"generate_web_assets: empty asset: {path}")

        identifier = to_identifier(path.name)
        # A name made only of punctuation would silently yield the symbol kGz.
        if not identifier:
            raise SystemExit(
                f"generate_web_assets: {path.name} has no alphanumeric "
                "characters to build a symbol from. Rename it.")
        # Punctuation collapses to nothing, so foo-bar.js and foo_bar.js both
        # want kFooBarJsGz. Say so here instead of letting the C++ compiler
        # report a duplicate definition of a symbol nobody wrote by hand.
        if identifier in claimed:
            raise SystemExit(
                f"generate_web_assets: {path.name} and {claimed[identifier]} "
                f"both map to the symbol k{identifier}Gz. Rename one of them.")
        claimed[identifier] = path.name

        assets.append((path.name, identifier, compress(raw)))
    if not assets:
        raise SystemExit(
            f"generate_web_assets: no assets found in {source_directory}")
    return assets


def render_header(assets) -> str:
    lines = [
        BANNER,
        "#pragma once",
        "",
        "#include <cstddef>",
        "",
        "namespace pf_web {",
        "namespace web_assets {",
        "",
    ]
    for name, identifier, payload in assets:
        lines.append(f"// {name} ({len(payload)} bytes gzipped)")
        lines.append(f"extern const unsigned char k{identifier}Gz[];")
        lines.append(f"extern const std::size_t k{identifier}GzSize;")
        lines.append("")
    lines.extend([
        "}  // namespace web_assets",
        "}  // namespace pf_web",
        "",
    ])
    return "\n".join(lines)


def render_source(assets) -> str:
    lines = [
        BANNER,
        '#include "web_assets_generated.hpp"',
        "",
        "namespace pf_web {",
        "namespace web_assets {",
        "",
    ]
    for name, identifier, payload in assets:
        lines.append(f"// {name}")
        lines.append(f"const unsigned char k{identifier}Gz[] = {{")
        for offset in range(0, len(payload), BYTES_PER_LINE):
            chunk = payload[offset:offset + BYTES_PER_LINE]
            body = ", ".join(f"0x{byte:02x}" for byte in chunk)
            lines.append(f"    {body},")
        lines.append("};")
        lines.append(
            f"const std::size_t k{identifier}GzSize = "
            f"sizeof(k{identifier}Gz);")
        lines.append("")
    lines.extend([
        "}  // namespace web_assets",
        "}  // namespace pf_web",
        "",
    ])
    return "\n".join(lines)


def write_if_changed(path: pathlib.Path, content: str) -> bool:
    if path.is_file() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="embed data/web into a generated C++ translation unit")
    parser.add_argument("--source-dir", type=pathlib.Path, required=True)
    parser.add_argument("--output-dir", type=pathlib.Path, required=True)
    parser.add_argument("--quiet", action="store_true")
    arguments = parser.parse_args()

    if not arguments.source_dir.is_dir():
        print(
            f"generate_web_assets: no such directory: {arguments.source_dir}",
            file=sys.stderr)
        return 1

    assets = collect(arguments.source_dir)
    changed = write_if_changed(
        arguments.output_dir / "web_assets_generated.hpp",
        render_header(assets))
    changed |= write_if_changed(
        arguments.output_dir / "web_assets_generated.cpp",
        render_source(assets))

    if not arguments.quiet:
        total = sum(len(payload) for _, _, payload in assets)
        state = "updated" if changed else "unchanged"
        print(
            f"generate_web_assets: {len(assets)} assets, "
            f"{total} bytes gzipped ({state})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
